spring:
  application:
    name: config-repo
  profiles:
    active: dev,mysql
  datasource:
    username: dbuser
    password: '{cipher}3970eda6f2032d5962c176dce6d5cf7ce03f60c6931fd9ef02c0bf0a823b4496'